### ISSUE TITLE
allow for `fixed(positive(1.0))` - apply `value` recursively?

### ISSUE THREAD

**Issue by st--** [invenia/ParameterHandling.jl#45]
To allow for specifying both that a parameter _should_ be positive, _and_ is currently not to be optimised over, it'd be great to support `fixed(positive(1.0))`. This could be achieved by applying `value` recursively (or at least twice, perhaps special-casing for `fixed`?).

Happy to provide a PR if you'd be willing to include it.

**Comment by willtebbutt** [comment]
A PR would be very welcome :)
